### ISSUE TITLE
Mongodb plugin?

### ISSUE THREAD

**Issue by atmosferia-projects** [meteofi/docker-geoserver#4]
Hi, great work and thanks for putting it available to others!

I've a container running your Geoserver distribution, but I don't see the mongodb plugin. Should I rebuild the docker image with the mongodb plugin installed?

Thanks

**Comment by atmosferia-projects** [comment]
Finally I modified the Dockerfile from geoserver 2.19 to add the mongo plugin; In 2.19/Dockerfile I modified ARG GEOSERVER_PLUGINS to add the mongodb plugin

ARG GEOSERVER_PLUGINS="css grib netcdf pyramid vectortiles wps ysld **mongodb**"

**Comment by mrauhala** [comment]
Sorry did not notice these mails earlier. Yes I removed mongodb at some point since it created some instability. Forgot to update README. Since GEOSERVER_PLUGINS is ARG. You don't have to modify Dockerfile, just build with commanline argument --build-arg GEOSERVER_PLUGINS="css grib netcdf pyramid vectortiles wps ysld mongodb"
